apiVersion: v1
kind: Service
metadata:
  name: id-pain
  namespace: id-pain
spec:
  selector:
    app: id-pain
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  type: ClusterIP
