#!/usr/bin/env python3
"""
{{COMPANY_NAME}} — {{USE_CASE}} Synthetic Trace Generator

Architecture: {{ARCHITECTURE}}
Framework:    {{FRAMEWORK}}
Generated by: arize-synthetic-demo skill

Emits OpenInference traces to Arize AX via arize-otel. Use for demos and workshops.

Usage:
  python generator.py --test                      # one trace per scenario type
  python generator.py --count 500                 # full batch
  python generator.py --count 500 --with-evals    # plus trace/span/session evals
  python generator.py --count 100 --seed 42       # reproducible subset
  python generator.py --project-name custom_proj  # override project

  # Dataset + experiment grid (NEW)
  python generator.py --build-dataset                 # write dataset.csv locally
  python generator.py --build-dataset --upload        # also upload via `ax`
  python generator.py --build-experiments             # write experiments/runs_*.json
  python generator.py --build-experiments --upload    # also create 4 experiments via `ax`
  python generator.py --build-prompts                 # write prompts/*.json locally
  python generator.py --build-prompts --upload        # also upload v1.0+v2.0 to Prompt Hub
  python generator.py --full                          # traces + evals + dataset + experiments + prompts
"""

import argparse
import json
import os
import random
import time
from collections import Counter
from contextlib import contextmanager
from pathlib import Path

from dotenv import load_dotenv

load_dotenv(Path(__file__).parent / ".env")

from arize.otel import register
from opentelemetry import trace
from opentelemetry.trace.status import Status, StatusCode


# ─── OpenInference attribute keys ─────────────────────────────────────────────

_KIND = "openinference.span.kind"
_INPUT = "input.value"
_OUTPUT = "output.value"
_INPUT_MIME = "input.mime_type"
_OUTPUT_MIME = "output.mime_type"
_JSON = "application/json"
_TEXT = "text/plain"


# ─── Provider metadata (fill from references/frameworks.md) ──────────────────

LLM_MODEL = "{{LLM_MODEL}}"          # e.g. "gpt-4o-mini", "claude-3-5-sonnet-latest", "gemini-2.0-flash"
LLM_PROVIDER = "{{LLM_PROVIDER}}"    # e.g. "openai", "anthropic", "google", "aws"
LLM_SYSTEM = "{{LLM_SYSTEM}}"        # e.g. "openai", "anthropic", "vertexai", "bedrock"
LLM_SPAN_NAME = "{{LLM_SPAN_NAME}}"  # e.g. "ChatCompletion", "Messages", "AsyncGenerateContent"


# ─── Domain content bank ─────────────────────────────────────────────────────
# <<<FILL: 10-20 realistic queries + expected answers for this company/use case>>>

QUERY_BANK = [
    # {
    #     "question": "<user query>",
    #     "answer": "<expected agent answer>",
    #     "tool_calls": [  # tool calls this scenario should produce
    #         {"name": "get_account_balance", "input": {"account_id": "a_123"},
    #          "output": {"balance": 2481.55, "currency": "USD"}},
    #     ],
    #     "retrieved_docs": [   # only for rag/rag_rerank/guarded_rag
    #         {"id": "d1", "content": "...", "score": 0.92},
    #     ],
    #     "complexity": "simple",   # simple | aggregation | multi_hop
    # },
]

AMBIGUOUS_QUERIES = [
    # {"question": "...", "clarification_question": "...", "clarified_question": "...",
    #  "ambiguity_reason": "...", "answer": "..."}
]

NO_LLM_QUERIES = [
    # {"question": "...", "answer": "..."}  # trivial Qs that skip the agent
]


# ─── Prompt templates ────────────────────────────────────────────────────────
# <<<FILL: 1-3 named prompt templates with system_message, template, version>>>

PROMPT_TEMPLATES = {
    # "template_name": {
    #     "template": "User question: {user_query}\nContext: {context}",
    #     "system_message": "You are a {role} for {{COMPANY_NAME}}...",
    #     "version": "v1.0",
    # },
}

PROMPT_VERSIONS = {"v1.0": 0.70, "v2.0": 0.30}


# ─── Tools ───────────────────────────────────────────────────────────────────
# <<<FILL: 4-8 tools with realistic names, descriptions, param schemas>>>

TOOLS = {
    # "get_account_balance": {
    #     "name": "get_account_balance",
    #     "description": "Retrieve the current balance for a specified account.",
    #     "parameters": {
    #         "type": "object",
    #         "properties": {"account_id": {"type": "string"}},
    #         "required": ["account_id"],
    #     },
    # },
}


# ─── Poisoned data config (optional cost-anomaly demo) ───────────────────────

POISONED_DATA = {
    "enabled": True,
    "poisoned_agents": {
        # "agent_name": {"probability": 0.10, "prompt_tokens": 55000, "completion_tokens": 18000},
    },
    "default_prompt_tokens": 50000,
    "default_completion_tokens": 20000,
}


# ─── Helpers ─────────────────────────────────────────────────────────────────

@contextmanager
def timer():
    start = time.time()
    yield
    print(f"Execution time: {time.time() - start:.2f}s")


def _span_id(span):
    return format(span.get_span_context().span_id, "016x")


def _set_kind(span, kind):
    span.set_attribute(_KIND, kind)


def _set_io(span, input_val, output_val):
    if input_val is not None:
        if isinstance(input_val, str):
            span.set_attribute(_INPUT, input_val)
            span.set_attribute(_INPUT_MIME, _TEXT)
        else:
            span.set_attribute(_INPUT, json.dumps(input_val))
            span.set_attribute(_INPUT_MIME, _JSON)
    if output_val is not None:
        if isinstance(output_val, str):
            span.set_attribute(_OUTPUT, output_val)
            span.set_attribute(_OUTPUT_MIME, _TEXT)
        else:
            span.set_attribute(_OUTPUT, json.dumps(output_val))
            span.set_attribute(_OUTPUT_MIME, _JSON)


def _set_llm_attrs(span, *, system_msg, user_msg, assistant_msg,
                   prompt_tokens=None, completion_tokens=None,
                   template=None, template_version=None, template_vars=None,
                   is_poisoned=False):
    span.set_attribute(_KIND, "LLM")
    span.set_attribute("llm.model_name", LLM_MODEL)
    span.set_attribute("llm.provider", LLM_PROVIDER)
    span.set_attribute("llm.system", LLM_SYSTEM)

    idx = 0
    if system_msg:
        span.set_attribute(f"llm.input_messages.{idx}.message.role", "system")
        span.set_attribute(f"llm.input_messages.{idx}.message.content", system_msg)
        idx += 1
    span.set_attribute(f"llm.input_messages.{idx}.message.role", "user")
    span.set_attribute(f"llm.input_messages.{idx}.message.content", user_msg)
    span.set_attribute("llm.output_messages.0.message.role", "assistant")
    span.set_attribute("llm.output_messages.0.message.content", assistant_msg)

    if is_poisoned:
        pt = prompt_tokens or random.randint(50000, 80000)
        ct = completion_tokens or random.randint(15000, 25000)
    else:
        pt = prompt_tokens if prompt_tokens is not None else random.randint(150, 600)
        ct = completion_tokens if completion_tokens is not None else random.randint(40, 300)
    span.set_attribute("llm.token_count.prompt", pt)
    span.set_attribute("llm.token_count.completion", ct)
    span.set_attribute("llm.token_count.total", pt + ct)

    if template:
        span.set_attribute("llm.prompt_template.template", template)
    if template_version:
        span.set_attribute("llm.prompt_template.version", template_version)
    if template_vars:
        span.set_attribute("llm.prompt_template.variables", json.dumps(template_vars))


def _set_tool_attrs(span, *, tool_name, input_val, output_val,
                    is_mcp=False, mcp_server=None, mcp_version="1.0"):
    span.set_attribute(_KIND, "TOOL")
    span.set_attribute("tool.name", tool_name)
    _set_io(span, input_val, output_val)
    if is_mcp and mcp_server:
        span.set_attribute("mcp.server.name", mcp_server)
        span.set_attribute("mcp.server.version", mcp_version)


def _annotate_session(span, session_id):
    if session_id:
        span.set_attribute("session.id", session_id)


def _mark_error(span, exc_type, exc_message):
    span.set_status(Status(StatusCode.ERROR, exc_message))
    span.add_event("exception", attributes={
        "exception.type": exc_type,
        "exception.message": exc_message,
    })


# ─── Architecture-specific span emitters ─────────────────────────────────────
# <<<FILL: paste the appropriate snippet from templates/snippets/*.py.snippet>>>
# - single_agent.py.snippet
# - multi_agent.py.snippet
# - rag.py.snippet
# - rag_rerank.py.snippet
# - guarded_rag.py.snippet


# ─── create_trace and scenario flows ─────────────────────────────────────────
# <<<FILL: implement create_trace(tracer, scenario, session_id) that branches on
#          scenario["type"] ∈ {happy_path, tool_failure, guardrail_denial,
#                              ambiguity, execution_failure, retry,
#                              poisoned_tokens, no_llm_needed}
#          and returns {"root": <span_id>, ...} for eval attachment>>>


# ─── Scenario builder ────────────────────────────────────────────────────────

def build_scenarios(count, seed=None):
    if seed is not None:
        random.seed(seed)
    scenarios = []
    for _ in range(count):
        r = random.random()
        if   r < 0.45: stype = "happy_path"
        elif r < 0.55: stype = "tool_failure"
        elif r < 0.63: stype = "guardrail_denial"
        elif r < 0.71: stype = "ambiguity"
        elif r < 0.79: stype = "execution_failure"
        elif r < 0.87: stype = "retry"
        elif r < 0.95: stype = "poisoned_tokens"
        else:           stype = "no_llm_needed"

        if stype == "ambiguity" and AMBIGUOUS_QUERIES:
            q = random.choice(AMBIGUOUS_QUERIES)
        elif stype == "no_llm_needed" and NO_LLM_QUERIES:
            q = random.choice(NO_LLM_QUERIES)
        else:
            q = random.choice(QUERY_BANK) if QUERY_BANK else {"question": "?", "answer": "..."}

        prompt_version = "v1.0" if random.random() < PROMPT_VERSIONS.get("v1.0", 0.70) else "v2.0"

        scenarios.append({
            **q,
            "type": stype,
            "prompt_version": prompt_version,
            "is_poisoned": stype == "poisoned_tokens",
        })
    return scenarios


# ─── Evaluations (optional) ──────────────────────────────────────────────────
# <<<FILL: implement generate_evaluations(span_data_list) that returns
#          (span_eval_df, trace_eval_df, session_eval_df) — see references/evaluations.md>>>


def _dummy_eval(scenario, pass_rate=0.80):
    will_pass = random.random() < pass_rate
    return {
        "label": "pass" if will_pass else "fail",
        "score": 0 if will_pass else 1,
        "explanation": (
            f"Reviewed scenario '{scenario.get('type')}' with question "
            f"\"{scenario.get('question', '')[:80]}\". "
            + ("The trace followed the expected pattern." if will_pass
               else "The trace deviated from the expected pattern at one or more steps.")
        ),
    }


def generate_evaluations(span_data_list):
    """Default implementation — attach one trace_eval per trace.

    Override or extend to add span-level / session-level evals per architectures.md.
    """
    import pandas as pd

    trace_rows = []
    session_rows = []

    for sd in span_data_list:
        scenario = sd["scenario"]
        root_sid = sd.get("root_span_id", "")
        if not root_sid:
            continue
        ev = _dummy_eval(scenario)
        trace_rows.append({
            "context.span_id": root_sid,
            "trace_eval.TrajectoryAccuracy.label": ev["label"],
            "trace_eval.TrajectoryAccuracy.score": ev["score"],
            "trace_eval.TrajectoryAccuracy.explanation": ev["explanation"],
        })

    session_groups = {}
    for sd in span_data_list:
        sid = sd.get("session_id", "")
        if not sid:
            continue
        session_groups.setdefault(sid, []).append(sd)

    for sid, traces in session_groups.items():
        first_root = traces[0].get("root_span_id", "")
        if not first_root:
            continue
        ev = _dummy_eval({"type": "session", "question": f"{len(traces)} turns"})
        session_rows.append({
            "context.span_id": first_root,
            "session_eval.SessionResolution.label": ev["label"],
            "session_eval.SessionResolution.score": ev["score"],
            "session_eval.SessionResolution.explanation": ev["explanation"],
        })

    span_df = pd.DataFrame()   # populate in architecture-specific impls
    trace_df = pd.DataFrame(trace_rows) if trace_rows else pd.DataFrame()
    session_df = pd.DataFrame(session_rows) if session_rows else pd.DataFrame()
    return span_df, trace_df, session_df


# ─── Batch runner ────────────────────────────────────────────────────────────

def run_batch(tracer, count=500, *, with_evals=False, project_name=None, session_size=(3, 6)):
    scenarios = build_scenarios(count)
    span_data_list = []

    print(f"Generating {count} synthetic traces...")
    dist = Counter(s["type"] for s in scenarios)
    print("  Scenario distribution:")
    for stype, cnt in sorted(dist.items(), key=lambda x: -x[1]):
        print(f"    {stype}: {cnt} ({cnt/count*100:.0f}%)")
    print()

    session_id = None
    traces_in_session = 0
    current_session_size = 0

    with timer():
        for i, scenario in enumerate(scenarios):
            if session_id is None or traces_in_session >= current_session_size:
                session_id = f"session_{random.randint(100000, 999999)}"
                current_session_size = random.randint(*session_size)
                traces_in_session = 0

            result = create_trace(tracer, scenario, session_id=session_id)
            traces_in_session += 1
            span_data_list.append({
                "root_span_id": result.get("root", ""),
                "scenario": scenario,
                "session_id": session_id,
                **{k: v for k, v in result.items() if k not in ("root", "final_answer")},
            })

            if ((i + 1) % 100 == 0) or (i + 1 == count):
                print(f"  Created {i+1}/{count} traces...")

        print("\nFlushing spans...")
        flush_timeout = min(30000 + (count // 100) * 5000, 300000)
        ok = trace.get_tracer_provider().force_flush(timeout_millis=flush_timeout)
        print(f"  {'Flush successful' if ok else 'Flush timeout (some spans may still be in flight)'}.")

    if with_evals and span_data_list:
        print("\nWaiting 10s for spans to be indexed before logging evaluations...")
        time.sleep(10)
        print(f"Generating evaluations for {len(span_data_list)} traces...")
        span_df, trace_df, session_df = generate_evaluations(span_data_list)
        print(f"  {len(span_df)} span evals, {len(trace_df)} trace evals, {len(session_df)} session evals.")

        space_id = os.environ.get("ARIZE_SPACE_ID", "")
        api_key = os.environ.get("ARIZE_API_KEY", "")
        if space_id and api_key and project_name:
            try:
                from arize.pandas.logger import Client
                client = Client(space_id=space_id, api_key=api_key)
                if len(span_df):
                    client.log_evaluations_sync(span_df, project_name)
                    print(f"  Logged {len(span_df)} span evaluations.")
                if len(trace_df):
                    client.log_evaluations_sync(trace_df, project_name)
                    print(f"  Logged {len(trace_df)} trace evaluations.")
                if len(session_df):
                    client.log_evaluations_sync(session_df, project_name)
                    print(f"  Logged {len(session_df)} session evaluations.")
                print(f"  All evaluations logged to project '{project_name}'.")
            except Exception as e:
                print(f"  Error logging evaluations: {e}")


# ─── Dataset + experiment grid ───────────────────────────────────────────────
# <<<FILL: paste templates/snippets/dataset_experiments.py.snippet here, then
#          fill MODEL_FAMILY_GRID / MODEL_LABELS / EXPERIMENT_PROMPT_TEMPLATE_NAME
#          per references/datasets-experiments.md>>>


# ─── CLI ─────────────────────────────────────────────────────────────────────

DEFAULT_PROJECT_NAME = "{{PROJECT_NAME}}"
DEFAULT_DATASET_NAME = "{{DATASET_NAME}}"   # e.g. "<company_slug>_eval_set"
DEFAULT_PROMPT_NAME  = "{{PROMPT_NAME}}"    # e.g. "<company_slug>_<template_name>"
# Model slug used in the prompt-hub entry (playground default). Should match the
# "strong" model the demo highlights. <<<FILL: e.g. anthropic.claude-3-5-sonnet-20241022-v2:0>>>
DEFAULT_PROMPT_MODEL = "<<<FILL: e.g. anthropic.claude-3-5-sonnet-20241022-v2:0>>>"


def _need_creds():
    space_id = os.environ.get("ARIZE_SPACE_ID", "")
    api_key = os.environ.get("ARIZE_API_KEY", "")
    if not space_id or not api_key:
        print("Error: ARIZE_SPACE_ID and ARIZE_API_KEY must be set (see .env.example).")
        raise SystemExit(1)
    return space_id, api_key


def main():
    parser = argparse.ArgumentParser(description="{{COMPANY_NAME}} synthetic trace generator")
    parser.add_argument("--count", type=int, default=500)
    parser.add_argument("--test", action="store_true", help="Emit one trace per scenario type")
    parser.add_argument("--with-evals", action="store_true")
    parser.add_argument("--project-name",
                        default=os.environ.get("ARIZE_PROJECT_NAME", DEFAULT_PROJECT_NAME))
    parser.add_argument("--seed", type=int, default=None)

    # Dataset + experiment grid
    parser.add_argument("--build-dataset", action="store_true",
                        help="Build dataset.csv from QUERY_BANK rows")
    parser.add_argument("--build-experiments", action="store_true",
                        help="Build experiment runs files (4 cells: 2 models x 2 prompts)")
    parser.add_argument("--upload", action="store_true",
                        help="Upload dataset + experiments to Arize via `ax` CLI")
    parser.add_argument("--build-prompts", action="store_true",
                        help="Write prompts/*.json and optionally upload to the Arize Prompt Hub")
    parser.add_argument("--full", action="store_true",
                        help="Traces + evals + dataset + experiments + prompts (all uploaded if creds present)")
    parser.add_argument("--dataset-name", default=DEFAULT_DATASET_NAME)
    parser.add_argument("--dataset-id", default=None,
                        help="Reuse an existing Arize dataset id (skip dataset upload)")
    parser.add_argument("--prompt-name", default=DEFAULT_PROMPT_NAME)
    parser.add_argument("--prompt-model", default=DEFAULT_PROMPT_MODEL)

    args = parser.parse_args()

    if args.seed is not None:
        random.seed(args.seed)

    # ── --full: do everything end-to-end ──────────────────────────────────
    if args.full:
        space_id, _ = _need_creds()
        register(space_id=space_id, api_key=os.environ["ARIZE_API_KEY"],
                 project_name=args.project_name)
        tracer = trace.get_tracer(__name__)

        print("=== STEP 1/4: traces + evals ===")
        run_batch(tracer, count=args.count, with_evals=True, project_name=args.project_name)

        print("\n=== STEP 2/4: dataset ===")
        ds_id = args.dataset_id
        if not ds_id:
            ds_id, _ = build_dataset_and_upload(
                dataset_name=args.dataset_name, space_id=space_id, upload=True)
        else:
            print(f"  Reusing existing dataset id: {ds_id}")

        print("\n=== STEP 3/4: experiment grid (2 models x 2 prompts) ===")
        if ds_id:
            run_experiment_grid(dataset_id=ds_id, dataset_name=args.dataset_name,
                                space_id=space_id, upload=True)
        else:
            print("  No dataset_id available — skipping experiment uploads.")

        print("\n=== STEP 4/4: prompt hub ===")
        upload_prompts_via_ax(prompt_name=args.prompt_name, space_id=space_id,
                              model=args.prompt_model, upload=True)
        print("\nDone.")
        return

    # ── --build-dataset (with optional --upload) ──────────────────────────
    if args.build_dataset:
        space_id = os.environ.get("ARIZE_SPACE_ID", "")
        ds_id, _ = build_dataset_and_upload(
            dataset_name=args.dataset_name, space_id=space_id, upload=args.upload)
        if ds_id:
            print(f"\nDataset id: {ds_id}")
            print(f"Re-use it for experiments:  python generator.py --build-experiments --upload --dataset-id {ds_id}")
        return

    # ── --build-experiments (with optional --upload) ──────────────────────
    if args.build_experiments:
        space_id = os.environ.get("ARIZE_SPACE_ID", "")
        if args.upload and not args.dataset_id:
            print("Error: --upload requires --dataset-id (run --build-dataset --upload first).")
            raise SystemExit(1)
        run_experiment_grid(dataset_id=args.dataset_id, dataset_name=args.dataset_name,
                            space_id=space_id, upload=args.upload)
        return

    # ── --build-prompts (with optional --upload) ──────────────────────────
    if args.build_prompts:
        space_id = os.environ.get("ARIZE_SPACE_ID", "")
        upload_prompts_via_ax(prompt_name=args.prompt_name, space_id=space_id,
                              model=args.prompt_model, upload=args.upload)
        return

    # ── trace flow (existing) ─────────────────────────────────────────────
    space_id, _ = _need_creds()
    register(space_id=space_id, api_key=os.environ["ARIZE_API_KEY"],
             project_name=args.project_name)
    tracer = trace.get_tracer(__name__)

    if args.test:
        print("Running test traces (one per scenario type)...\n")
        scenario_types = ["happy_path", "tool_failure", "ambiguity",
                          "execution_failure", "retry", "poisoned_tokens", "no_llm_needed"]
        span_data_list = []
        for stype in scenario_types:
            base = QUERY_BANK[0] if QUERY_BANK else {"question": "test", "answer": "test"}
            scenario = {**base, "type": stype, "prompt_version": "v1.0", "is_poisoned": stype == "poisoned_tokens"}
            sess = "test_session"
            result = create_trace(tracer, scenario, session_id=sess)
            print(f"  {stype}: root={result.get('root')}")
            span_data_list.append({"root_span_id": result.get("root", ""), "scenario": scenario, "session_id": sess})
        trace.get_tracer_provider().force_flush(timeout_millis=30000)
        print("\nTest traces flushed. Check your Arize project.")
    else:
        run_batch(tracer, count=args.count, with_evals=args.with_evals, project_name=args.project_name)

    print("\nDone.")


if __name__ == "__main__":
    main()
